block_labels = ["needs-decision", "S-waiting-on-team"]
delete_merged_branches = true
required_approvals = 1
timeout_sec = 14400
status = [
  "build (1.56.0)",
  "build (stable)",
  "test",
  "test-strict",
]
