[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
description = "A CMSIS-SVD file parser"
documentation = "https://docs.rs/svd-parser"
keywords = ["CMSIS", "SVD", "parser"]
license = "MIT OR Apache-2.0"
name = "svd-parser"
repository = "https://github.com/japaric/svd"
edition = "2018"
version = "0.7.0"

[features]
derive-from = []
unproven = []

[dependencies]
either = "1.5"
xmltree = "0.8"
failure = "0.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[dev-dependencies]
serde_json = "1.0"

[[example]]
name = "svd2json"
required-features = ["serde"]
